export const moves = [
  { name: "Meia lua de frente", type: "Circular Kicks", description: "", link:"https://www.youtube.com/watch?v=UzG2bNa4CrE"},
  { name: "Queixada", type: "Circular Kicks", description: "Outside crescent kick ", link: "https://www.youtube.com/watch?v=H3pQJc8d8H8" },
  { name: "Armada", type: "Circular Kicks", description: "A spinning outside crescent kick common to regionall games.From the ginga execute the entrada: then rotate your head and torso about 180 degrees until you can see your target.There should be acorresponding spin of your feet then the kick is released using the heel to impact your target", link: "https://www.youtube.com/watch?v=1iJ_pBo-Isc" },
  { name: "Meia lua de compasso", type: "Circular Kicks", description: "", link: "https://www.youtube.com/watch?v=IiLqVCyyoPs" },
  { name: "Benção", type: "Straight Kicks", description: " Front push kick. The bencao can be executed with either the lead or rear leg, simply draw your knee close to your body then push out with your foot in a stomping while leaning your shoulders back.The point of contact is the heel or the sole of the foot. ", link: "https://www.youtube.com/watch?v=Qz5dtM5XnTQ" },
  { name: "Pisão", type: "Straight Kicks", description: "", link: "https://www.youtube.com/watch?v=Hrwx81ePVlY" },
  { name: "Na frente", type: "Esquivas", description: "", link: "" },
  { name: "Da ginga", type: "Esquivas", description: "", link: "" },
  { name: "Lateral", type: "Esquivas", description: "", link: "https://www.youtube.com/watch?v=iuebJy4_JFQ&t=4s" },
  { name: "Ginga", type: "Standing Movements", description: "To ginga start with your feet roughly shoulders width apart.Imagine that your are standing on the base of an equilateral triangle with the apex bisecting your centerline.Make sure that your legs are slightly bent and that the rest of your body is relaxed. Take one foot and slide - step from the base to the apex of the imaginary triangle. You should be in a position akin to a deep lunge.Make sure that your hands are protecting your face and that your legs are slightly bent and that your are the balls of your feet.Return your foot to the base then swing the other one to the apex.Your body should swing side to side, continue this motion in time with the music.This is the basic frame work for the ginga, although the ginga is chiefly a lateral movement you should be able to advance, retreat, and circle your partner.When you are comfortable with the pasada you can move on to the second aspect of the ginga the balanco", link: "https://www.youtube.com/watch?v=HbUxXJKitS4" },
  { name: "Passada lateral", type: "Standing Movements", description: "", link: "" },
  { name: "Troca de base", type: "Standing Movements", description: "", link: "" },
  { name: "Troca diagonal", type: "Standing Movements", description: "", link: "" },
  { name: "Pula na frente", type: "Standing Movements", description: "", link: "" },
  { name: "Pula lateral", type: "Standing Movements", description: "", link: "" },
  { name: "Puxeta (Puxada)", type: "Standing Movements", description: "", link: "" },
  { name: "Negativa", type: "Ground Movements", description: " A way of escaping an attack by dropping to the ground.The negative can be used as a means to setup a counter attack.There are a few variations of this movement below is a description of three most commonly used in Capoeira Da Rua.", link: "https://www.youtube.com/watch?v=iRb8inBYpf0" },
  { name: "Rolêr", type: "Ground Movements", description: "", link: "https://www.youtube.com/watch?v=YkjKw8FPA6Y" },
  { name: "Finta de apanhada", type: "Ground Movements", description: "", link: "" },
  { name: "Gira de quadrilho", type: "Ground Movements", description: "", link: "" },
  { name: "Passada nas costas", type: "Ground Movements", description: "", link: "" },
  { name: "Ponte", type: "", description: "", link: "https://www.youtube.com/watch?v=INFUiJLaclo" },
  { name: "Queda de rins", type: "Floreios", description: "", link: "" },
  { name: "Standard Aú", type: "Floreios", description: "First assume your neutral stance with your feet spread a little more than Shoulder width apart.Then lean to the side and place one hand on ground, Continue looking forward then hop onto the hand that is planted.As your body swings over place your other hand on the ground to balance your weight and to aid you as you land.Make sure that your feet are bent in front of you or tucked above.As you land place one foot down at a time, then resume your ginga. ", link: "https://www.youtube.com/watch?v=e79asoU7TUs" },
  { name: "Headstand", type: "Floreios", description: "", link: "https://www.youtube.com/watch?v=I2xjozih7-s" },
  { name: "Standard", type: "Entradas", description: "", link: "https://www.youtube.com/watch?v=q3ElxkeFJns" },
  { name: "De traz (No entrance)", type: "Entradas", description: "", link: "" },
  { name: "Avançando", type: "Entradas", description: "", link: "" },
  { name: "Standard (Back)", type: "Finishing Positions for Kicks", description: "", link: "" },
  { name: "Parallel", type: "Finishing Positions for Kicks", description: "", link: "" },
  { name: "Frente", type: "Finishing Positions for Kicks", description: "", link: "" },
  { name: "Descida Trocando", type: "Dynamic Ground Movement", description: "", link: "" },
  { name: "Rolêr direito", type: "Dynamic Ground Movement", description: " A role like movement in which you place one hand on the ground and walk yourself around in a crouch while keeping your hand in place", link: "" },
  { name: "Aú negativa rolêr", type: "Transition Movements", description: "", link: "" },
];

export function getMoves() {
  return moves.map(m => m);
}
