export const moves = [
  { id: 1, name: "Meia lua de frente", type: "Circular Kicks", description: "", link: "https://www.youtube.com/watch?v=UzG2bNa4CrE" },
  { id: 2, name: "Queixada", type: "Circular Kicks", description: "Outside crescent kick ", link: "https://www.youtube.com/watch?v=H3pQJc8d8H8" },
  { id: 3, name: "Armada", type: "Circular Kicks", description: "A spinning outside crescent kick common to regionall games.From the ginga execute the entrada: then rotate your head and torso about 180 degrees until you can see your target.There should be acorresponding spin of your feet then the kick is released using the heel to impact your target", link: "https://www.youtube.com/watch?v=1iJ_pBo-Isc" },
  { id: 4, name: "Meia lua de compasso", type: "Circular Kicks", description: "", link: "https://www.youtube.com/watch?v=IiLqVCyyoPs" },
  { id: 5, name: "Benção", type: "Straight Kicks", description: " Front push kick. The bencao can be executed with either the lead or rear leg, simply draw your knee close to your body then push out with your foot in a stomping while leaning your shoulders back.The point of contact is the heel or the sole of the foot. ", link: "https://www.youtube.com/watch?v=Qz5dtM5XnTQ" },
  { id: 6, name: "Pisão", type: "Straight Kicks", description: "", link: "https://www.youtube.com/watch?v=Hrwx81ePVlY" },
  { id: 7, name: "Lateral", type: "Esquivas", description: "", link: "https://www.youtube.com/watch?v=iuebJy4_JFQ&t=4s" },
  { id: 8, name: "Ginga", type: "Standing Movements", description: "To ginga start with your feet roughly shoulders width apart.Imagine that your are standing on the base of an equilateral triangle with the apex bisecting your centerline.Make sure that your legs are slightly bent and that the rest of your body is relaxed. Take one foot and slide - step from the base to the apex of the imaginary triangle. You should be in a position akin to a deep lunge.Make sure that your hands are protecting your face and that your legs are slightly bent and that your are the balls of your feet.Return your foot to the base then swing the other one to the apex.Your body should swing side to side, continue this motion in time with the music.This is the basic frame work for the ginga, although the ginga is chiefly a lateral movement you should be able to advance, retreat, and circle your partner.When you are comfortable with the pasada you can move on to the second aspect of the ginga the balanco", link: "https://www.youtube.com/watch?v=HbUxXJKitS4" },
  { id: 9, name: "Negativa", type: "Ground Movements", description: " A way of escaping an attack by dropping to the ground.The negative can be used as a means to setup a counter attack.There are a few variations of this movement below is a description of three most commonly used in Capoeira Da Rua.", link: "https://www.youtube.com/watch?v=iRb8inBYpf0" },
  { id: 10, name: "Rolêr", type: "Ground Movements", description: "", link: "https://www.youtube.com/watch?v=YkjKw8FPA6Y" },
  { id: 11, name: "Finta de Apanhada/Descida (Deep Lunge)", type: "Ground Movements", description: "This movement is also called pay me know, or pay me later. In Capoeira, you will spend a lot of time in this position in order to transition to ground movements.", link: "" },
  { id: 12, name: "Ponte (Bridge)", type: "", description: "This position is fundamental to accomplish many Capoeira flourish movements. Tightness in the chest, shoulders, and upper back can make it difficult to execute the movement. Let your instructor know if you experience pain during this movement, and point out the exact place. It’s okay to start in a modified position as you build up your abilities.", link: "https://www.youtube.com/watch?v=INFUiJLaclo" },
  { id: 13, name: "Standard Aú", type: "Floreios", description: "First assume your neutral stance with your feet spread a little more than Shoulder width apart.Then lean to the side and place one hand on ground, Continue looking forward then hop onto the hand that is planted.As your body swings over place your other hand on the ground to balance your weight and to aid you as you land.Make sure that your feet are bent in front of you or tucked above.As you land place one foot down at a time, then resume your ginga. ", link: "https://www.youtube.com/watch?v=e79asoU7TUs" },
  { id: 14, name: "Headstand", type: "Floreios", description: "", link: "https://www.youtube.com/watch?v=I2xjozih7-s" },
  { id: 15, name: "Standard", type: "Entradas", description: "", link: "https://www.youtube.com/watch?v=q3ElxkeFJns" },
  { id: 16, name: "Rolêr direito", type: "Dynamic Ground Movement", description: " A role like movement in which you place one hand on the ground and walk yourself around in a crouch while keeping your hand in place", link: "" },
  { id: 17, name: "Au", type: "Transition Movements", description: "Aú is fundamental to the game of capoeira. It’s how you will enter the roda to begin your game in most cases. You used to perform cartwheels all the time as a child. In Capoeira, the aú is about elegance and strategic movement. Keep your head in between your arms and do not hyperextend your neck. Land standing upright with 10-20º flexion in your knees. Keep your spine in a neutral position, and always keep you eyes on your opponent. What you should be able to do first: Hold the cartwheel position with your leg in the air for at least 5 seconds without your leg lowering and your palm flat on the ground.Prep should also include leg straightening activities", link: "https://www.youtube.com/watch?v=e79asoU7TUs" },
  { id: 18, name: "Aú negativa rolêr", type: "Transition Movements", description: "", link: "" },
  { id: 19, name: "Na frente", type: "Esquivas", description: "", link: "" },
  { id: 20, name: "Da ginga", type: "Esquivas", description: "", link: "" },
  { id: 21, name: "Passada lateral", type: "Standing Movements", description: "", link: "" },
  { id: 22, name: "Troca de base", type: "Standing Movements", description: "", link: "" },
  { id: 23, name: "Troca diagonal", type: "Standing Movements", description: "", link: "" },
  { id: 24, name: "Pula na frente", type: "Standing Movements", description: "", link: "" },
  { id: 25, name: "Pula lateral", type: "Standing Movements", description: "", link: "" },
  { id: 26, name: "Puxeta (Puxada)", type: "Standing Movements", description: "", link: "" },
  { id: 27, name: "Gira de quadrilho", type: "Ground Movements", description: "", link: "" },
  { id: 28, name: "Passada nas costas", type: "Ground Movements", description: "", link: "" },
  { id: 29, name: "Standard (Back)", type: "Finishing Positions for Kicks", description: "", link: "" },
  { id: 30, name: "Parallel", type: "Finishing Positions for Kicks", description: "", link: "" },
  { id: 31, name: "Frente", type: "Finishing Positions for Kicks", description: "", link: "" },
  { id: 32, name: "Descida Trocando", type: "Dynamic Ground Movement", description: "", link: "" },
  { id: 33, name: "De traz (No entrance)", type: "Entradas", description: "", link: "" },
  { id: 34, name: "Avançando", type: "Entradas", description: "", link: "" },
  { id: 35, name: "Queda de rins", type: "Floreios", description: "", link: "" }
];

export function getMoves() {
  return moves.map(m => m);
}
